name: recipedient
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  sqflite: ^1.1.5
  path_provider: ^1.1.0
  intl: ^0.15.8
  cupertino_icons: ^0.1.2
  url_launcher: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: 0.7.0

flutter:

  uses-material-design: true

  assets:
    - resources/logo2.png
    - resources/bg.png
    - resources/edamam.png

