import 'recipe.dart';

List<Recipe> getRecipes() {
  return [
    Recipe(
        "https://biggreyhorse.com/2013/02/08/blue-bonnet-cafe-marble-falls/",
        "French Fries w/ Pepper",
        "https://biggreyhorse.com/wp-content/uploads/2012/11/10-22-2012-109-300x224.jpg",
        "https://biggreyhorse.com/2013/02/08/blue-bonnet-cafe-marble-falls/",
        "morphine.com",
        "",
        0,
        List<String>(),
        List(),
        ['french fries', 'pepper'],
        ['french fries, pepper'],
        List()),
    Recipe(
        "",
        "Savoy Truffle",
        "https://imgix.ranker.com/user_node_img/3234/64672977/original/savoy-truffle-songs-photo-u1?q=50&fm=pjpg",
        "",
        "beatles.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "",
        "Custard Pie",
        "https://cdn.magicskillet.com/wp-content/uploads/2018/01/easy-egg-custard-pie-recipe.jpg",
        "",
        "ledzep.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "https://www.bbcgoodfood.com/recipes/2177/roast-goose-with-potato-and-stuffing",
        "Baked Goose",
        "https://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--2285_11.jpg",
        "https://www.bbcgoodfood.com/recipes/2177/roast-goose-with-potato-and-stuffing",
        "gooseiscooked.com",
        "",
        0,
        List<String>(),
        List(),
        ['goose', 'onion', 'butter', 'apples'],
        ['goose, onion, butter, apples'],
        List()),
    Recipe(
        "",
        "Chocolate Cake",
        "https://sugarspunrun.com/wp-content/uploads/2017/02/easy-chocolate-cake-with-chocolate-buttercream-frosting-1-of-1-7.jpg",
        "",
        "chocolate.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "",
        "Peaches",
        "https://www.halegroves.com/images/m/9411-peaches.jpg",
        "",
        "tpotus.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "",
        "Ham Sandwich",
        "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/190322-ham-sandwich-horizontal-1553721016.png",
        "",
        "hamsandwich.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "",
        "Bacon Bread",
        "https://chezcateylou.files.wordpress.com/2013/08/img_5959.jpg",
        "",
        "bacon.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "",
        "Green Eggs",
        "https://eatingrichly.com/wp-content/uploads/2018/01/green-eggs-ham-9036-800x533.jpg",
        "",
        "seuss.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "",
        "Tupelo Honey",
        "https://cdn.apartmenttherapy.info/image/fetch/f_auto,q_auto:eco,c_fill,g_auto,w_1160/https://storage.googleapis.com/gen-atmedia/3/2009/04/8e8592b36585a04189892a73a05ec2e14cd73f9d.jpeg",
        "",
        "vanmor.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "",
        "Fried Green Tomatoes",
        "https://www.browneyedbaker.com/wp-content/uploads/2013/07/fried-green-tomatoes-6-600.jpg",
        "",
        "fgt.com",
        "",
        0,
        List<String>(),
        List(),
        List(),
        List(),
        List()),
    Recipe(
        "https://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--2285_11.jpg",
        "Fried Eggs",
        "https://i.dietdoctor.com/wp-content/uploads/2015/11/DD-13.jpg",
        "https://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--2285_11.jpg",
        "eggs.com",
        "",
        0,
        List<String>(),
        List(),
        ['eggs', 'oil'],
        ['eggs, oil'],
        List()),
  ];
}
